import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local"
import "./globals.css";
import {cn} from "@/lib/utils"
import {Toaster } from "@/components/ui/sonner"
import { dbConnect} from "@/service/mongo";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CodeLMS : One Stop Platform for Students",
  description: "Generated by create next app",
};
const poppins = Inter({subsets : ['latin'], variable:"--font-poppins"});

export default async function RootLayout({ children }) {
  
  const conn = await dbConnect();
  //console.log(conn);
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased, poppins.className`}
      >
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
